---
# defaults file for swarms
swarm_interface: "{{ ansible_default_ipv4['interface'] }}"
swarm_address: "{{ hostvars[inventory_hostname]['ansible_' + swarm_interface]['ipv4']['address'] }}"
swarm_address_manager: "{{hostvars[groups['manager'][0]]['ansible_default_ipv4']['address']}}" 
swarm_port: 2377
docker_compose_version: "1.26.2"
