---
- name: Create a directory if it does not exist
  file:
    path: /opt/stack-monitoring/prometheus
    state: directory
    mode: "0755"

- name: Add prometheus.yml"
  template:
    src: "prometheus.yml"
    dest: "/opt/stack-monitoring/prometheus/prometheus.yml"
    owner: root
    group: root

- name: Add docker-compose.yml"
  copy:
    src: "../files/docker-compose.yml"
    dest: "/opt/stack-monitoring/docker-compose.yml"
    owner: root
    group: root

- name: Run `docker-compose up` again
  shell: "docker stack deploy --compose-file /opt/stack-monitoring/docker-compose.yml stack-monitoring"
  when: "inventory_hostname == groups['manager'][0]"

- name: Restart prometheus
  uri:
    url: "http://{{groups['manager'][0]}}:9090/-/reload"
    method: POST
  retries: 10
  delay: 2
  when: "inventory_hostname == groups['manager'][0]"
