---
- name: Create a directory if it does not exist
  file:
    path: /opt/stack-monitoring/prometheus
    state: directory
    mode: "0755"
  when: "inventory_hostname == groups['manager'][0]"

- name: Add prometheus.yml"
  template:
    src: "prometheus.yml"
    dest: "/opt/stack-monitoring/prometheus/prometheus.yml"
    owner: root
    group: root
  when: "inventory_hostname == groups['manager'][0]"

- name: Add docker-compose.yml"
  copy:
    src: "../files/docker-compose.yml"
    dest: "/opt/stack-monitoring/docker-compose.yml"
    owner: root
    group: root
  when: "inventory_hostname == groups['manager'][0]"

- name: Run `docker-compose up` again
  shell: "docker stack deploy --compose-file /opt/stack-monitoring/docker-compose.yml stack-monitoring"
  when: "inventory_hostname == groups['manager'][0]"

- name: Download portainer-agent-stack.yml
  get_url:
    url: https://downloads.portainer.io/portainer-agent-stack.yml
    dest: /tmp/portainer-agent-stack.yml
    mode: "0755"
  when: "inventory_hostname == groups['manager'][0]"

- name: Run `portainer-agent-stack.yml` again
  shell: "docker stack deploy --compose-file=/tmp/portainer-agent-stack.yml portainer"
  when: "inventory_hostname == groups['manager'][0]"
  notify: restart Prometheus
