---
- name: Create a directory if it does not exist
  file:
    path: /opt/stack-monitoring/prometheus
    state: directory
    mode: "0755"
  when: "inventory_hostname == manager"

- name: Add prometheus.yml
  template:
    src: prometheus.yml
    dest: /opt/stack-monitoring/prometheus/prometheus.yml
    force: yes
  register: info_config_prometheus
  when: "inventory_hostname == manager"

- name: Get services running
  shell: "docker service ls --format {% raw %}'{{.Name}}'{% endraw %}"
  register: running_service_names
  changed_when: False
  when: "inventory_hostname == manager"

- name: Removing the Prometheus service
  shell: "docker service rm stack-monitoring_prometheus"
  when: "info_config_prometheus.changed 
  and running_service_names is search('monitoring_prometheus')"

- name: Deleting the outdated configuration
  shell: "docker config rm stack-monitoring_config_prometheus"
  when: "info_config_prometheus.changed 
  and running_service_names is search('monitoring_prometheus')"

- name: Add docker-compose.yml"
  copy:
    src: docker-compose.yml
    dest: /opt/stack-monitoring/docker-compose.yml
    owner: root
    group: root
  when: "inventory_hostname == manager"

- name: Deploy stack - monitoring
  shell: "docker stack deploy --compose-file /opt/stack-monitoring/docker-compose.yml stack-monitoring"
  when: "inventory_hostname == manager"
  notify: restart Prometheus

- name: Download portainer-agent-stack.yml
  get_url:
    url: https://downloads.portainer.io/portainer-agent-stack.yml
    dest: /tmp/portainer-agent-stack.yml
    mode: 0755
  when: "inventory_hostname == manager"

- name: Deploy portainer-agent-stack
  shell: "docker stack deploy --compose-file=/tmp/portainer-agent-stack.yml portainer"
  when: "inventory_hostname == manager"
