---
- name: restart Prometheus
  uri:
    url: "http://{{hostvars[manager]['ansible_default_ipv4']['address']}}:9090/-/reload"
    method: POST
    status_code:
      - -1
      - 200
  retries: 15
  delay: 5
  when: "inventory_hostname == manager"
