global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093


scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
    - targets: ["{{groups['manager'][0]}}:9090"]

  - job_name: 'node-exporter'
    scrape_interval: 5s
    static_configs:
    - targets:
      {% for m in groups['monitoring'] %}
      - {{ hostvars[m]['ansible_default_ipv4']['address']}}:9100
      {% endfor %}

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
        - "cadvisor:8080"