version: "3.7"
services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    ports:
      - 9090:9090
    depends_on:
      - cadvisor
    configs:
      - source: config_prometheus
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus:/prometheus
    networks:
      - monitor-net
    deploy:
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - monitor-net
    deploy:
      placement:
        constraints:
          - node.role==worker
      restart_policy:
        condition: on-failure

  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - monitor-net
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

configs:
  config_prometheus:
    file: /opt/stack-monitoring/prometheus/prometheus.yml 

volumes:
  prometheus:
    driver: rexray
  grafana:
    driver: rexray

networks:
  monitor-net:
